analyze_text_task:
  description: >
    Analyze the following tweet text and list the main points being communicated, presenting them clearly and concisely, specially if there are any metrics or numbers.
    The tweet text is: {topic}.
  expected_output: A list of main points being communicated.
  agent: text_analyzer


verify_important_task:
  description: >
    From the main points you've listed, keep only the points that public would want to know more about or generaly would not be aware of.
  expected_output: A list of points that public would want to know more about.
  agent: credibility_verifier


select_objective_task:
  description: >
    Out of the input data keep only the points that are objective and should be verified for credibility. Remove any points that are subjective or opinion based.
  expected_output: A list of points that should be verified for credibility.
  agent: objective_selector
